### ISSUE TITLE
incoming single b3 header is ignored

### ISSUE THREAD

**Issue by tajdars** [openzipkin-contrib/brave-kafka-interceptor#1]
I am using CP : 5.1.2 and kafka-interceptor-zipkin-0.4.3-SNAPSHOT.jar

Connector sinks from JMS to Kafka.
Incoming JMS message has a single B3 header setup :

b3 
db767712d91f0bc8-db767712d91f0bc8-1

This is valid as per 
https://github.com/openzipkin/b3-propagation

But Connector generates new Trace ignoring this,

Thoughts ?

**Comment by jeqo** [comment]
We do extract context from headers on Kafka Source Connector (ie `TracingProducerInterceptor`). If context is not available a new trace is created. Just added a test to validate this: https://github.com/sysco-middleware/kafka-interceptor-zipkin/commit/6db99317c381ea1881b18418bd6dd1dca480c942

In order to make the trick, JMS Connector should pass JMS header into Kafka header following zipkin format.

Could you share which connector are you using?

**Comment by tajdars** [comment]
I am using the Kafka JMS Connector  ver 5.1.2

https://docs.confluent.io/current/connect/kafka-connect-jms/index.html

The b3 single header is present in the incoming jms message as 

b3
db767712d91f0bc8-db767712d91f0bc8-1

Not separate headers.

**Comment by jeqo** [comment]
That I understand. What I mean is how the incoming JMS headers that you mention is mapped into a Kafka one. Is not clear from documentation that is a direct mapping: https://docs.confluent.io/current/connect/kafka-connect-jms/index.html#io-confluent-connect-jms-propertyvalue or that headers are used at all.

Does any or your JMS headers appear as Kafka headers? or are they available on the payload (kafka record value)?

**Comment by tajdars** [comment]
I manged to get this to work by writing a custom Kafka Connect Transformer (I was using a configured Transformer previously).
The transformer copies the b3 Struct string from the properties Map to a Header property (key is b3)
Things flow from here.

Not sure if there are other/ better approaches.

**Comment by jeqo** [comment]
That sounds like the proper approach to me. I'd say it would be better to map properties to headers directly as part of the Connector, but that should be discussed on the JMS Connector repo.

Glad is working now, I will close this issue.
