### ISSUE TITLE
kafka authentication jaas

### ISSUE THREAD

**Issue by msillence** [openzipkin-contrib/brave-kafka-interceptor#14]
## Feature
Confluent cloud requires jass authentication to send messages

## Rationale
Jass is a supported authentication mechanism for kafka

## Example Scenario
anyone wanting to secure their tracing and monitoring solution

## Details

typically you need to configure:
```
zipkin.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<username>" password="<password>";
zipkin.sasl.mechanism=PLAIN
zipkin.security.protocol=SASL_SSL
```

Optionally:
`zipkin.ssl.endpoint.identification.algorithm=https`

in addition to the existing:
`zipkin.bootstrap.servers=<host>:<port>`

**Comment by jeqo** [comment]
@msillence this is hopefully solved with #17, could you give a try with v0.6.0?

**Comment by msillence** [comment]
Sorry, finally found time to test this and it works perfectly! thanks!

**Comment by msillence** [comment]
for anyone looking the following config:
```
zipkin.kafka.bootstrap.servers=pkc-l6wr6.europe-west2.gcp.confluent.cloud:9092
zipkin.kafka.sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username="<user>" password="<password>";
zipkin.kafka.sasl.mechanism=PLAIN
zipkin.kafka.security.protocol=SASL_SSL
```
