### ISSUE TITLE
publishing artifacts to Bintray

### ISSUE THREAD

**Issue by jeqo** [openzipkin-contrib/brave-kafka-interceptor#5]
I haven't been able to deploy releases to Bintray/JCenter. Currently getting the following exception:
https://travis-ci.org/openzipkin-contrib/brave-kafka-interceptor/builds/609786080?utm_medium=notification&utm_source=github_status

```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:3.0.0-M1:deploy (default-deploy) on project brave-kafka-interceptor: 
ArtifactDeployerException: Failed to deploy artifacts: Could not transfer artifact io.zipkin.contrib.brave:brave-kafka-interceptor:jar:0.5.3 from/to bintray (https://api.bintray.com/maven/openzipkin-contrib/maven/brave-kafka-interceptor/;publish=1): 
Failed to transfer file https://api.bintray.com/maven/openzipkin-contrib/maven/brave-kafka-interceptor/;publish=1/io/zipkin/contrib/brave/brave-kafka-interceptor/0.5.3/brave-kafka-interceptor-0.5.3.jar with status code 409 -> [Help 1]
```

cc @abesto

**Comment by abesto** [comment]
ACK. Just moved to a new flat this weekend so hands are pretty full, but will try to look in a reasonable timeframe. Won't be offended if someone else fixes it meanwhile.

**Comment by jeqo** [comment]
@abesto no rush :) good luck in your move!

**Comment by abesto** [comment]
@jeqo Things are settling down, just a few boxes around the flat now :D Some time has passed, I'm seeing the latest builds passing. Confirm this isn't an issue anymore?

**Comment by jeqo** [comment]
I've tried to restart this build but still failing https://travis-ci.org/openzipkin-contrib/brave-kafka-interceptor/builds/609786080. 
But we can check once we do a new release.

**Comment by jeqo** [comment]
Ref this is fixed: https://www.travis-ci.org/openzipkin-contrib/brave-kafka-interceptor/builds/646149442
